# Generated by Django 6.1.1 on 2026-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('memory', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('regular_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('screen_diagonal', models.CharField(blank=True, max_length=50)),
                ('screen_resolution', models.CharField(blank=True, max_length=100)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
